name: Gerar metricas do perfil

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    if: ${{ secrets.METRICS_TOKEN != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Gerar painel de metricas
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: mathvll
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
